let shopItemsDeta = [
	{
		id: "100",
		name: " T-shirt",
		price: 40,
		des: "lorem Lorem ipsum dolor, sit amet consectetur adipisicing.",
		img: "img/adstore1.avif",
	},
	{
		id: "255",
		name: "Formal Shirt",
		price: 60,
		des: "lorem Lorem ipsum dolor, sit amet consectetur adipisicing.",
		img: "img/adstore2.avif",
	},
	{
		id: "300",
		name: "Boys shoes",
		price: 70,
		des: "lorem Lorem ipsum dolor, sit amet consectetur adipisicing.",
		img: "img/adstore3.avif",
	},
	{
		id: "224",
		name: "Girls shoes",
		price: 90,
		des: "lorem Lorem ipsum dolor, sit amet consectetur adipisicing.",
		img: "img/adstore4.avif",
	},
	{
		id: "5",
		name: "Girls shoes",
		price: 90,
		des: "lorem Lorem ipsum dolor, sit amet consectetur adipisicing.",
		img: "img/adstore5.avif",
	},
	{
		id: "6",
		name: " Warm Winter Hats ",
		price: 90,
		des: "lorem Lorem ipsum dolor, sit amet consectetur adipisicing.",
		img: "img/adstore6.jpg",
	},
	{
		id: "7",
		name: "Converse",
		price: 90,
		des: "lorem Lorem ipsum dolor, sit amet consectetur adipisicing.",
		img: "img/adstore7.jpg",
	},
	{
		id: "8",
		name: "Men's Athletic Running Shorts",
		price: 90,
		des: "lorem Lorem ipsum dolor, sit amet consectetur adipisicing.",
		img: "img/adstore8.jpg",
	},
	{
		id: "9",
		name: "Suits",
		price: 90,
		des: "lorem Lorem ipsum dolor, sit amet consectetur adipisicing.",
		img: "img/9.jpg",
	},
	{
		id: "10",
		name: "Pants",
		price: 90,
		des: "lorem Lorem ipsum dolor, sit amet consectetur adipisicing.",
		img: "img/img-10.png",
	},
	{
		id: "11",
		name: "Caps",
		price: 90,
		des: "lorem Lorem ipsum dolor, sit amet consectetur adipisicing.",
		img: "img/img-11.png",
	},
	{
		id: "12",
		name: " Black Boots",
		price: 90,
		des: "lorem Lorem ipsum dolor, sit amet consectetur adipisicing.",
		img: "img/img-12.png",
	},
];
